project:
  type: website
  output-dir: docs

website:
  title: "PORTPOLIO_Youna"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - hw1.qmd
      - hw2.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



