project:
  type: website
  output-dir: docs

website:
  title: "PORTPOLIO_Youna"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: about
      - href: blog.qmd
        text: Blog


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



