project:
  type: website
  output-dir: docs

website:
  title: "PORTPOLIO_Youna"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: posts/index.qmd
        text: Blog
      - href: project.qmd
        text: Project


format:
  html:
    theme: Sandstone
    toc: true



